services:
  mysql:
    image: mysql:8.0
    container_name: licenses-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123!
      MYSQL_DATABASE:     description_db
      MYSQL_USER:         Desuser
      MYSQL_PASSWORD:     DesPassw0rd!
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3307:3307"
